version: '3.8'

services:
  clinic-server:
    build:
      context: ./clinic-server
    container_name: clinic-server
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - clinic-net

  clinic-client:
    build:
      context: ./clinic-client
    container_name: clinic-client
    ports:
      - "${CLIENT_PORT}:8080"
    depends_on:
      - clinic-server
    environment:
      CAMUNDA_API_URL: "http://clinic-server:8080/engine-rest"
    networks:
      - clinic-net

networks:
  clinic-net:
    driver: bridge
