spring:
  datasource:
    url: ${JDBC_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

camunda:
  bpm:
    database:
      type: postgres
    filter:
      create: All tasks
    auto-deployment-enabled: true
    admin-user:
      id: ${CAMUNDA_USER}
      password: ${CAMUNDA_PASSWORD}
      first-name: Admin
    job-execution:
      enabled: true
    default-serialization-format: application/json
    history-level: full
    deployment-resource-pattern: classpath*:processes/*.bpmn


logging:
  level:
    org.springframework.web.client.RestTemplate: TRACE


server:
  port: ${SERVER_PORT}


debug: true