name: Update Build Status Badge

on:
  push:
    paths:
      - 'resources/build-status.json'
    branches-ignore:
      - 'gh-pages'

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract status from resources/build-status.json
        run: |
          STATUS=$(jq -r '.message' resources/build-status.json)
          echo "status=$STATUS" >> "$GITHUB_ENV"

      - name: Build badge JSON
        run: |
          if [[ "${{ env.status }}" == "success" ]]; then
            echo '{"schemaVersion":1,"label":"build","message":"success","color":"green"}' > resources/build-badge.json
          else
            echo '{"schemaVersion":1,"label":"build","message":"failed","color":"red"}' > resources/build-badge.json
          fi

      - name: Commit & push badge
        if: github.actor != 'nektos/act'          # skip when running locally with act
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add resources/build-badge.json
          git commit -m "CI: update build badge" || echo "Nothing to commit"
          git push
